# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDahjBsL1Wu-kobfw622Tut0oe0-41_h
"""



n=int(input("enter number of modules"))
marks=[]
for i in range(n*2):
    e=int(input("Enter marks"))
    marks.append(e)
print(marks)

t=0
for j in range(0,n*2,2):
    if marks[j] >= marks[j+1]:
        t=t+marks[j]
    else:
        t=t+marks[j+1]
print("total mark=",t)