# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjDaMH8jv2fKeMYH8oRujSrYsdhXw9As
"""

txt=input("Enter Text")
s=''
x=txt.split()
for i in x:
  if i !='and' and i!='or' and i!='of':
    s+=i[0].upper()
print(s)